### ISSUE TITLE
Custom Tick mark option #ios

### ISSUE THREAD

**Issue by vrnDhmn** [prscX/react-native-bottom-action-sheet#13]
Right now, bottom sheet opens with first item as selected by default `√`.
It could be made optional to use.

**Comment by prscX** [comment]
Thanks @nuravdhiman for raising the issue.

Coming weekend I will look into the same and will share the updates. 

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @nuravdhiman, I have fixed and pushed a release `V0.0.10`. Let me know in case you still face the same issue.

Thanks
</ Pranav>
