### ISSUE TITLE
Android can't open sheet

### ISSUE THREAD

**Issue by topzerzar** [prscX/react-native-bottom-action-sheet#16]
Error Android only.

in build.gradle

```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven { url 'https://jitpack.io' }
    }
}
```

![screenshot_20180508-005952_gschool_react](https://user-images.githubusercontent.com/14545847/39716755-60cdad82-525b-11e8-85be-29980223f769.jpg)

**Comment by prscX** [comment]
Thanks @topzerzar for raising the issue. Looks like the library is not linked properly. Can you please run below command:

`react-native link react-native-bottom-action-sheet`

Please let me know in case you still face the same issue.

Thanks
</ Pranav >

**Comment by topzerzar** [comment]
I have follow you step but still fail like a photo above.

**Comment by progfiles** [comment]
Same thing. 
"error: cannot find symbol
            new RNBottomActionSheetPackage(),"

**Comment by progfiles** [comment]
I think because did not link "react-native link react-native-vector-icons"

**Comment by arma7x** [comment]
https://github.com/prscX/react-native-bottom-action-sheet/issues/24#issuecomment-445817864

**Comment by prscX** [comment]
Thanks @arma7x for sharing the solution.  Hope the issue was fixed. Closing the issue.

Thanks
</ Pranav >
