### ISSUE TITLE
Use non-vector images as icons, or use no icon

### ISSUE THREAD

**Issue by 404sand808s** [prscX/react-native-bottom-action-sheet#18]
Hi! Great component, install was a breeze and it's working perfectly.

The one thing I'm wondering is that my use case requires me to show custom images as icons in the Sheet View instead of the ones available in the compatible icon libraries. So far on Android returning null as an icon or removing icon altogether stops it from rendering. Is there a way I can use either a custom image or just use no icon?

Thanks!

**Comment by prscX** [comment]
Thanks @404sand808s for raising the issue.

I have added support for providing custom icons. Please refer `README`/`Example Project` in order to achieve the same.

Please let me know in case you face any issues.

[v0.0.12](https://github.com/prscX/react-native-bottom-action-sheet/releases/tag/v0.0.12)

Thanks
</ Pranav >

**Comment by 404sand808s** [comment]
Awesome, thank you very much!

**Comment by prscX** [comment]
Hi @404sand808s, I am looking into the issue when we provide no icon. Hopefully it will be fix by EOD.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @404sand808s, I have fixed the issue when icon is not provided. Can you please install [v0.0.13](https://github.com/prscX/react-native-bottom-action-sheet/releases/tag/v0.0.13) and verify the same.

Please let me know in case you face any issues.

Thanks
</ Pranav >

**Comment by 404sand808s** [comment]
Just tested, confirming that it works on Android with no icon — thanks for the super fast turnaround on this!

**Comment by prscX** [comment]
Thanks @404sand808s for validating and sharing the results.

Thanks
</ Pranav >
