### ISSUE TITLE
iOS GridView Chinese characters

### ISSUE THREAD

**Issue by rheng001** [prscX/react-native-bottom-action-sheet#21]
Hi, this is a great library! 

I have a slight issue when showing a GridView on an ios simulator/device. My GridView displays just as I want but there is some strange chinese characters on the bottom of the view. Is there any way I can remove  these? Its random and out of place. On my android device/emulator it doesnt display any chinese characters and works fine. 

Also the chinese text button below is messing up my items array.  I have 8 objects in the array,
```
items: [
        { title: "Food", icon: "food_icon.png" },
        { title: "Coffee Shops", icon: "coffee_icons.png" },
        { title: "Markets", icon: "market_icons.png" },
        { title: "Bus Stops", icon: "busstop_icons.png" },
        { title: "Libraries", icon: "libraries_icons.png" },
        { title: "Buildings", icon: "building_icons.png" },
        { title: "Parking", icon: "parking_icons.png" },
        { title: "Food Trucks", icon: "foodtruck_icons.png" },

      ]
```

 I have a switch case as follows for my 8 objects, starting at case 0 since arrays start at 0

```
 switch (selection) {
            case 0:
            case 1:
                 ....
                 ....
            case 7
}
```

However the chinese text button below actually counts as a selection item and when I alerted a message when I press on it says 0. This means that the first object in the array is actually the chinese text button. And when I click on my last object in my array I initialized(this case Food Trucks) it goes out of bounds and gives me an error since the selection is technically considered as (selection === 8)

![bottom](https://user-images.githubusercontent.com/14899915/42530323-c3cbdad8-8435-11e8-8781-0326dea26ea2.png)

**Comment by prscX** [comment]
Thanks @rheng001 for raising the issue.

I will look into this today and will push a new release with the fix.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @rheng001, I have made the required changes in the native library. Can you please verify by installing the library again. Please let me know incase you still face the same issue.

On the other note, when I am invoking Grid Alert it is giving me below layout, can you please share any fix you have made to the library:

<img width="618" alt="screen shot 2018-07-18 at 2 52 53 pm" src="https://user-images.githubusercontent.com/28862892/42872485-b0d80e9a-8a9a-11e8-8ab4-b897fbad6e14.png">
>

Thanks
</ Pranav

**Comment by rheng001** [comment]
Hi @prscX 

I tried installing the library again and there were no changes. I was looking through the recent commits and saw that there was no new commits regarding this change. I also looked on the npm site to see if the library verison was changed but its still the same.

Is this change live for me to download? How would I go about installing the new changes? 

Thanks

**Comment by prscX** [comment]
Hi @rheng001: My bad, I forgot to mention the fix is done in the native library [prscX/SGActionView](https://github.com/prscX/SGActionView) - [COMMIT](https://github.com/prscX/SGActionView/commit/d3edaf178de6f7281c26533683bf388612e4019f). In order to upgrade this library there are two ways of doing it:

- Reinstall the library using `npm install` command, doing this it will automatically execute `pod install` command on iOS folder.
- Execute `pod install` command on the library `iOS` folder: 

`node_modules/react-native-bottom-action-sheet/ios/`

Thanks
</ Pranav >

**Comment by rheng001** [comment]
Hey @prscX 

I was able to grab the fix and it deleted the chinese characters successfully. However there is still a problem regarding the item array.

![simulator_screen_shot_-_iphone_6_-_2018-07-19_at_11 39 48](https://user-images.githubusercontent.com/14899915/42963575-74098b6a-8b49-11e8-98a0-042831004bb0.png)

I receive this error, because from my first post the Chinese cancel button is still taking up the item array[0] position. My Food Truck object should be items[0] but it is still considered to be items[1] and gives me errors.

I see from your code from https://github.com/prscX/SGActionView/commit/d3edaf178de6f7281c26533683bf388612e4019f#diff-2cbd6bf6bd77be3bcd32e9a084a4a0c6 you have removed the button view but not actual button implementation into the array. 

I think I have found the lines that you need to remove. The cancel button that you commented out from has the following code
https://github.com/prscX/SGActionView/blob/d3edaf178de6f7281c26533683bf388612e4019f/SGActionView/SGGridMenu.m#L94-L96

I believe these lines are still associated with the cancel_button that you commented out. 
https://github.com/prscX/SGActionView/blob/d3edaf178de6f7281c26533683bf388612e4019f/SGActionView/SGGridMenu.m#L123-L126

The cancel button is still being created functionally in the code and being added to the item array here with items[0]

![simulator_screen_shot_-_iphone_6_-_2018-07-19_at_11 13 56](https://user-images.githubusercontent.com/14899915/42963611-8fb9d87e-8b49-11e8-8893-0fb3cb173471.png)

**Comment by rheng001** [comment]
bump
