### ISSUE TITLE
Close event for RNBottomActionSheet.SheetView

### ISSUE THREAD

**Issue by TeruyaHaroldo** [prscX/react-native-bottom-action-sheet#26]
Hello!
Somebody knows how to get the close event when the user touch outside of the view?
Thanks!

**Comment by prscX** [comment]
Thanks @HaroldoTeruya for raising the query.

Currently it is not supported by native integrated libraries. 

Thanks
</ Pranav >

**Comment by apski** [comment]
OK but I have a problem where I have the sheet display once, then I move to another screen and when I return the action sheet is visible and not responsive to touch at all. I have to kill the app. 

I think this has to do with the sheetView state. How can I ensure the sheetView state is changed when I tap away from the sheetView to dismiss i.e. not tap option on sheet view? 

Edit: I had to setState to false when returning to the view that launches the sheetView.

**Comment by prscX** [comment]
@apski: Got you. If you are going through React way then you need to set the visibility false, however you can use static API as well which comes with handy usage.

Thanks 
</ Pranav >
