### ISSUE TITLE
Updating state when the bottom sheet is dismissed

### ISSUE THREAD

**Issue by naddeoa** [prscX/react-native-bottom-action-sheet#29]
Looking over the docs, I can't see how to tell when the bottom sheet is dismissed. I'm trying to take the React approach where the visibility state is managed in my component state, but I'm not sure how I'm supposed to update that visibility state to false when the user clicks the background to dismiss the bottom sheet without making a selection, and `onSelection` doesn't look like it gets called in that case.

How can I update my component state when the bottom sheet is dismissed?

**Comment by mtzfactory** [comment]
Yeah, that would be great...

**Comment by mtzfactory** [comment]
Hi,

I've just added a [PR](https://github.com/prscX/react-native-bottom-action-sheet/pull/36) solving this issue.

By!

**Comment by prscX** [comment]
Thanks @mtzfactory for sharing the PR and Effort.

Closing the issue since it was fixed in shared PR.

Thanks
</ Pranav >
