### ISSUE TITLE
icons are not displayed.

### ISSUE THREAD

**Issue by gayatrimhaske-eaton** [prscX/react-native-bottom-action-sheet#33]

**Comment by gayatrimhaske-eaton** [comment]
I am using bottomsheet - sheetview. and trying to display the icons. Somehow, icons are not displayed.  tried the same example given. bt its not working

**Comment by prscX** [comment]
Thanks @gayatribm for raising the issue.

Are you referring to iOS implementation? I am afraid to share, as part of current iOS implementation, we don't have support for rendering icons on iOS, it is only supported on Android.

Thanks
</ Pranav >

**Comment by gayatrimhaske-eaton** [comment]
Ok.. Thanks for the update.  Do you aware of any other lib of similar kind.

**Comment by prscX** [comment]
Hi @gayatribm: I believe, there are few JS based implementation libraries which supports your requirement, however I don't think we have any such native module library.

Thanks
</ Pranav >
