### ISSUE TITLE
Icons pixelated with poor quality

### ISSUE THREAD

**Issue by fgagneten** [prscX/react-native-bottom-action-sheet#34]
I've just downloaded the example project and it turned out that icons have a poor quality. (I will not paste code because is the same as the example project)

**Info**
**SO:** Android
**Brand:** Samsung S9
**Version:** 9.0
**react-native Version:** 0.58.6
**react-native-bottom-action-sheet Version**: 0.0.19
![screenshot_20190305-194916_dondejuego](https://user-images.githubusercontent.com/14353978/53843268-9c2bf100-3f80-11e9-8353-8b342f32d701.jpg)

Is there any solution for that? 

Thanks!

**Comment by prscX** [comment]
Thanks @fgagneten for raising the issue.

It is a know concern. Earlier I did looked into the same, but I was not able to fix the issue. If anyone found a fix please share the same.

Thanks
</ Pranav >

**Comment by fgagneten** [comment]
I think one of the problem is related to the library:
[BottomSheetBuilder]( https://github.com/rubensousa/BottomSheetBuilder)

I made a pull request  in **BottomSheetBuilder project** so we can fix a piece of the problem
[Pull Request #40](https://github.com/rubensousa/BottomSheetBuilder/pull/40)

**Comment by prscX** [comment]
Thanks @fgagneten for the Effort and PR.

I have created a native library fork and push the release with the fix. Could you please download latest version and verify the same.

Please let me know in case you still face the issue.

[v0.0.20](https://github.com/prscX/react-native-bottom-action-sheet/releases/tag/v0.0.20)

Thanks
</ Pranav >

**Comment by fgagneten** [comment]
Worked like a charm!
**Before 01**
![Before 01](https://user-images.githubusercontent.com/14353978/53995877-42106480-4115-11e9-8fc5-0fb937f63301.jpg)

**After 01**
![after 01](https://user-images.githubusercontent.com/14353978/53995906-61a78d00-4115-11e9-9970-4a107e077c7a.jpg)

**Before 02**
![before 02](https://user-images.githubusercontent.com/14353978/53995925-6cfab880-4115-11e9-9123-6180d6e11e06.jpg)

**After 02**
![after 02](https://user-images.githubusercontent.com/14353978/53995938-78e67a80-4115-11e9-8c65-ae1a8ae422a7.jpg)

Good coding!

**Comment by helenamcfreire** [comment]
I'm still having this issue. Tried icons from Material and Font Awesome, and it always get pixelated. I'm already on v0.0.20.

My code:

```
let importIcon = <MaterialIcons name={'cloud-upload'} color={'#706E70'} size={10} family={'MaterialIcons'} />
            let exportIcon = <MaterialIcons name={"cloud-download"} color={"#706E70"} size={10} family={"MaterialIcons"} />

            let SheetView = RNBottomActionSheet.SheetView
            SheetView.Show({
                title: "Choose...",
                items: [
                    { title: "Import", value: "import", subTitle: "Import Description", icon: importIcon},
                    { title: "Export", value: "export", subTitle: "Export Description", icon: exportIcon},
                ],
                theme: "light",
                selection: 3,
                onSelection: (index, value) => {
                    // value is optional
                    console.log("selection: " + index + " " + value);
                }
            });
        }
```

Screenshot:

![image](https://user-images.githubusercontent.com/2065160/54368276-9ace8880-4652-11e9-859f-dd6b94141f92.png)



Info
SO: Android
Brand: Motorola
Version: 7.0
react-native Version: 0.57.4
react-native-bottom-action-sheet Version: 0.0.20
