### ISSUE TITLE
titleTextColor not working for Android

### ISSUE THREAD

**Issue by thorakmedichi** [prscX/react-native-bottom-action-sheet#37]
RN 55.4
react-native-bottom-action-sheet: "0.0.20" (installed via yarn today - assuming most recent version)

itemTextColor works.... 
titleTextColor does not

Also onCancel doesn't seem to fire either for Android.

```
const BottomSheet = ({ isVisible }) => (
    <RNBottomActionSheet.SheetView
        visible={isVisible}
        title="Set Break"
        theme="dark"
        backgroundColor='black'
        titleTextColor='red'
        itemTextColor='red'
        onSelection={(index, value) => {
            // value is optional
            console.log("selection: " + index + " " + value); 
        }}
        onCancel={() => console.log ('canceled')}
    >
        <RNBottomActionSheet.SheetView.Item title="Lunch" />
        <RNBottomActionSheet.SheetView.Item title="Appointment" />
        <RNBottomActionSheet.SheetView.Item title="Errands" />
        <RNBottomActionSheet.SheetView.Item title="Vacation / Holiday" />
        <RNBottomActionSheet.SheetView.Item title="End of Work Day" />
    </RNBottomActionSheet.SheetView>
);
```

While I am at it is there a way to change the styling of each of the line items. There is waaaay too much padding between items for our liking.

**Comment by denisbevilacqua** [comment]
Same issue here!

**Comment by Dragollla** [comment]
In `RNBottomActionSheetModule` move
```
if (titleTextColor != null && titleTextColor.length() > 0) {
        bottomSheetBuilder = bottomSheetBuilder.setTitleTextColor(Color.parseColor(titleTextColor));
      }
``` 
before     
`  bottomSheetBuilder = bottomSheetBuilder.addTitleItem(title);`

I'll make a PR soon

**Comment by prscX** [comment]
@Dragollla: Thanks for sharing the fix here. Could you please raise PR. Will review and merge the same.

Thanks,
</ Pranav >

**Comment by Dragollla** [comment]
see PR [here](https://github.com/prscX/react-native-bottom-action-sheet/pull/66)

**Comment by prscX** [comment]
Thanks @Dragollla for sharing the PR. I have merged the same.

Thanks,
</ Pranav >
