### ISSUE TITLE
buildToolsVersion is not specified

### ISSUE THREAD

**Issue by oonxt** [prscX/react-native-bottom-action-sheet#4]
react-native run-android:

> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-bottom-action-sheet'.
      > buildToolsVersion is not specified.

**Comment by prscX** [comment]
Thanks @oonxt for rising the issue.

I will add the missing `buildToolsVersion` and publish the same.

Thanks 
Pranav

**Comment by prscX** [comment]
Hi @oonxt, I have added the buildToolsVersion in build.gradle and published it with V0.0.4

Can you please install and verify the same. Let me know if you still face the same issue.

Thanks
Pranav
