### ISSUE TITLE
Could not resolve com.github.prscx:bottomsheetbuilder:fixes-SNAPSHOT.

### ISSUE THREAD

**Issue by nilocoelhojunior** [prscX/react-native-bottom-action-sheet#41]
Hi guys, I try to run my project today and get this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not resolve com.github.prscx:bottomsheetbuilder:fixes-SNAPSHOT.
  Required by:
      project :app > project :react-native-bottom-action-sheet
   > Skipped due to earlier error
```

React version:
```
"react": "16.6.1",
"react-native": "0.57.7",
```

My react-native-bottom-action-sheet:

```
react-native-bottom-action-sheet@^0.0.20:
  version "0.0.20"
  resolved "https://registry.yarnpkg.com/react-native-bottom-action-sheet/-/react-native-bottom-action-sheet-0.0.20.tgz#f0200ff4d6f92ed2616d602cddd183eeb5fd8308"
  integrity sha512-vrhkporSCESJARB8wiMKSJWrM4DzgyYu0j4zbNcaSa49m93B/SEmWu0lv3Rt9F//pYo0m5umxYWMBJH2sliLJw==
  dependencies:
    pod-installer "0.0.0"
    react-native-vector-icons "5.0.0"
```

How I can to fix?

**Comment by ivanguimam** [comment]
same problem

**Comment by Hel5ing** [comment]
replace "yourproject\node_module\react-native-bottom-action-sheet\android\build.gradle" line 41
**implementation 'com.github.prscx:bottomsheetbuilder:fixes-SNAPSHOT'**
with
**implementation 'com.github.rubensousa:bottomsheetbuilder:1.6.1'**

**Comment by prscX** [comment]
@nilocoelhojunior:  Please add below snippet to your `build.gradle`:

```
allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
    }
}
```

**Comment by tmaly1980** [comment]
> @nilocoelhojunior: Please add below snippet to your `build.gradle`:
> 
> ```
> allprojects {
>     repositories {
>         maven { url 'https://jitpack.io' }
>     }
> }
> ```

@prscX That's not the problem. The problem is bottomsheetbuilder:fixes-SNAPSHOT is no longer available. The library needs to be updated to reference that other library.

When I notice gradle is retrieving https://dl.google.com/dl/android/maven2/com/github/prscx/bottomsheetbuilder/fixes-SNAPSHOT/maven-metadata.xml , it gets a 404.
