### ISSUE TITLE
Move SGActionView.

### ISSUE THREAD

**Issue by Lxxyx** [prscX/react-native-bottom-action-sheet#5]
SGActionView is in ios/podfile, every time install this module have to install SGActionView again.

Can user add it by himself? Not when install the module.

**Comment by prscX** [comment]
Thanks @Lxxyx for suggesting the improvement.

I have removed `postinstall` script from `package.json`, now we need to manually install iOS library pods using below command:

`cd ./node_modules/react-native-bottom-action-sheet/ios/ && pod install`

Can you please download latest V0.0.5 and verify the same. Please let me know in case you still face any issues.

Thanks
Pranav
