### ISSUE TITLE
Multi select option 

### ISSUE THREAD

**Issue by ilibilibom** [prscX/react-native-bottom-action-sheet#57]
Is there a way to a multiselect option (with checkmarks) to RNbas ?
Here is my current code: 
```
<RNBottomActionSheet.SheetView
          visible={true}
          title={'Awesome!'}
          theme={'light'}
          onSelection={(index, value) => {
            // value is optional
            console.log('selection: ' + index + ' ' + value);
          }}>
          <RNBottomActionSheet.SheetView.Item
            title={'Facebook'}
            value="facebook"
            subTitle={'Facebook Description'}
            icon={facebook}
          />
          <RNBottomActionSheet.SheetView.Item
            title={'Instagram'}
            value="Instagram"
            subTitle={'Instagram Description'}
            icon={instagram}
          />
        </RNBottomActionSheet.SheetView>
```
2 more questions: 
1) Why is value undefined in onSelection ?
2) Is there a way to show custom images in sheet view ?

**Comment by ilibilibom** [comment]
Also - why is value undefined in onSelection ?

**Comment by prscX** [comment]
@ilibilibom: Please find below my response:

- This library tries to native single selection UI component using native libraries. Multi Selection is not supported by this library.

- Custom Images are not supported through JS layer, however you can copy the custom image in apps resource container and provide its reference from your app. Please refer README/Example project for the same.

Thanks
</ Pranav >
