### ISSUE TITLE
Can't run on Android

### ISSUE THREAD

**Issue by wkwyatt** [prscX/react-native-bottom-action-sheet#6]
Getting this error and not able to perform `run-android`

```
Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.github.javiersantos:BottomDialogs:1.2.1.
     Required by:
         myApp:app:unspecified > myApp:react-native-bottom-action-sheet:unspecified
```

**Comment by prscX** [comment]
Thanks @wkwyatt for raising the issue.

My bad. I forgot to add below snippet in `README` installation steps. Can you please verify by adding below snippet in your app `build.gradle` file:

```
allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
    }
}
```

Please let me know in case it does not work.

Thanks
Pranav

**Comment by wkwyatt** [comment]
Yes @prscX !  that got it working thank you
