### ISSUE TITLE
Missing dependency declare for react-native-image-helper

### ISSUE THREAD

**Issue by pqminh** [prscX/react-native-bottom-action-sheet#61]
Missing dependency for react-native-image-helper
"name": "react-native-bottom-action-sheet",
"version": "2.0.1",

**Comment by prscX** [comment]
@pqminh: `react-native-image-helper` is a peer dependency from `V2.*` onwards. You need to install the same. Please refer installation steps as per README. Let me  know incase it does not work.

Thanks
</ Pranav >
