### ISSUE TITLE
Bugs on android 4.4.2

### ISSUE THREAD

**Issue by arma7x** [prscX/react-native-bottom-action-sheet#7]
Icon does not appear in release build but works properly in debug. itemTintColor & itemTextColor doesn't works on android. I can only change backgroundColor

**Comment by prscX** [comment]
[+] @danielang

Thanks @arma7x for raising the issue.

Looks like it is similar to [react-native-popover-menu: issue-11](https://github.com/prscX/react-native-popover-menu/issues/11).

I have done a detailed research for [issue-11](https://github.com/prscX/react-native-popover-menu/issues/11) but I was not able to find the right solution. Basically in native we receive image url which is working as excepted in debug mode but on production it is not able to find the image.

One of the possible workaround I was thinking was to migrate to [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons). Doing this we will only be able to show icons provided by this library. Please let me know your views for the same.

Thanks
Pranav

**Comment by arma7x** [comment]
Maybe the issue was related to this https://github.com/facebook/react-native/issues/9451. I check in folder `../android/app/build/intermediates/res/merged/release` and my icon only copied to folder drawable-mdpi, not to folders drawable-hdpi, drawable-xhdpi and drawable-xxhdpi.

**Comment by prscX** [comment]
Hi @arma7x, I have enabled the support for [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons), now you will be able to integrate and use their icons. Please follow `README` in order to use the same. 

Can you please install latest version and verify the same. Please let me know in case you face any issues.

Thanks
Pranav

**Comment by arma7x** [comment]
Thank for update, will test it soon.

**Comment by prscX** [comment]
Hi @arma7x,  I have also fixed `itemTintColor` & `itemTextColor` prop which was not working.

Let me know in case you face any issues.

Thanks
</ Pranav >

**Comment by arma7x** [comment]
Thanks @prscX. Everything works.
