### ISSUE TITLE
GridView and SheetView callback onSelection not working 

### ISSUE THREAD

**Issue by arma7x** [prscX/react-native-bottom-action-sheet#8]
https://github.com/prscX/react-native-bottom-action-sheet/blob/master/js/GridView.js#L65
https://github.com/prscX/react-native-bottom-action-sheet/blob/master/js/SheetView.js#L79

Both should be `props.onSelection && props.onSelection(selection); ` instead of `props._onSelection && props._onSelection(selection); ` as in READ.ME guide.

**Comment by prscX** [comment]
Thanks @arma7x for the raising the issue.

My Bad. Your observation is right. I will fix and push the release together with [ISSUE: 7](https://github.com/prscX/react-native-bottom-action-sheet/issues/7).

Thanks
Pranav

**Comment by prscX** [comment]
Hi @arma7x, I have fixed and released `V0.0.7`. Can you please download latest version and verify the same.

Please let me know in case you face any issues.

Thanks
</ Pranav >

**Comment by arma7x** [comment]
Thanks @prscX
